version: 2.1
workflows:
  smn_workflow:
    jobs:
      - build:
          filters:
            branches:
              only: dev
      - test-python-install:
          version: "3.6"
          requires:
            - build
      - test-python-install:
          version: "3.7"
          requires:
            - build
      - deploy:
          requires:
            - build

jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "setup.py" }}
      - run:
          name: install python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: v1-dependency-cache-{{ checksum "setup.py" }}
          paths:
            - "venv"
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            echo "skip test"
      - store_artifacts:
          path: htmlcov/

  test-python-install:
    parameters:
      version:
        type: string
        default: latest
    docker:
      - image: circleci/python:<< parameters.version >>
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "setup.py" }}
      - run:
          name: install python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: v1-dependency-cache-{{ checksum "setup.py" }}
          paths:
            - "venv"
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            echo "skip test"
  deploy:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "setup.py" }}
      - run:
          name: install python dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: v1-dependency-cache-{{ checksum "setup.py" }}
          paths:
            - "venv"
      - run:
          name: init .pypirc
          command: |
            echo -e "[distutils]" >> ~/.pypirc
            echo -e "index-servers = pypi" >> ~/.pypirc
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "repository = https://upload.pypi.org/legacy/" >> ~/.pypirc
            echo -e "username = __token__ >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: install upload requirements
          command: |
            . venv/bin/activate
            pip install --upgrade pip
            pip install twine setuptools wheel

      - run:
          name: upload to pypi
          command: |
            . venv/bin/activate
            pwd
            ls -la
            cat ~/.pypirc
            python setup.py sdist bdist_wheel
            twine upload --repository-url  https://upload.pypi.org/legacy/ dist/*
